from PySide6.QtCore import QCoreApplication

# 給 pyside6-lupdate 用的，不會被實際執行
if False:
    QCoreApplication.translate("schema_config", "書籍資訊")
    QCoreApplication.translate("schema_config", "標題")
    QCoreApplication.translate("schema_config", "系列名稱")
    QCoreApplication.translate("schema_config", "系列分組")
    QCoreApplication.translate("schema_config", "風格類型")
    QCoreApplication.translate("schema_config", "集數編號")
    QCoreApplication.translate("schema_config", "總集數")
    QCoreApplication.translate("schema_config", "卷/冊號")
    QCoreApplication.translate("schema_config", "頁數")
    QCoreApplication.translate("schema_config", "格式描述")
    QCoreApplication.translate("schema_config", "語言 (ISO 639)")
    QCoreApplication.translate("schema_config", "替代版本")
    QCoreApplication.translate("schema_config", "替代系列名稱")
    QCoreApplication.translate("schema_config", "替代集數")
    QCoreApplication.translate("schema_config", "替代總集數")
    QCoreApplication.translate("schema_config", "內容摘要")
    QCoreApplication.translate("schema_config", "簡介")
    QCoreApplication.translate("schema_config", "備註")
    QCoreApplication.translate("schema_config", "評論")
    QCoreApplication.translate("schema_config", "角色與劇情")
    QCoreApplication.translate("schema_config", "登場角色")
    QCoreApplication.translate("schema_config", "主角或主團隊")
    QCoreApplication.translate("schema_config", "故事主軸")
    QCoreApplication.translate("schema_config", "地點")
    QCoreApplication.translate("schema_config", "出場團隊")
    QCoreApplication.translate("schema_config", "內容屬性")
    QCoreApplication.translate("schema_config", "黑白色彩")
    QCoreApplication.translate("schema_config", "是否為漫畫")
    QCoreApplication.translate("schema_config", "年齡分級")
    QCoreApplication.translate("schema_config", "創作團隊")
    QCoreApplication.translate("schema_config", "作者")
    QCoreApplication.translate("schema_config", "畫者 (鉛筆)")
    QCoreApplication.translate("schema_config", "墨線師")
    QCoreApplication.translate("schema_config", "上色師")
    QCoreApplication.translate("schema_config", "字體設計")
    QCoreApplication.translate("schema_config", "封面設計")
    QCoreApplication.translate("schema_config", "編輯")
    QCoreApplication.translate("schema_config", "出版資訊")
    QCoreApplication.translate("schema_config", "出版社")
    QCoreApplication.translate("schema_config", "品牌 / 出版系列")
    QCoreApplication.translate("schema_config", "網站")
    QCoreApplication.translate("schema_config", "出版年")
    QCoreApplication.translate("schema_config", "出版月")
    QCoreApplication.translate("schema_config", "出版日")
    QCoreApplication.translate("schema_config", "掃描資訊")
    QCoreApplication.translate("send_message", "錯誤")
    QCoreApplication.translate("send_message", "提示")
    QCoreApplication.translate("send_message", "完成")
    QCoreApplication.translate("send_message", "請選擇輸出資料夾")
    QCoreApplication.translate("send_message", "請選擇漫畫資料夾")
    QCoreApplication.translate("send_message", "請至少選擇一個檔案進行處理")
    QCoreApplication.translate("send_message", "所有漫畫處理完成！")
    QCoreApplication.translate("ui_constants", "ComicInfo 編輯器")
    QCoreApplication.translate("ui_constants", "列表")
    QCoreApplication.translate("ui_constants", "編輯")
    QCoreApplication.translate("ui_constants", "設定")
    QCoreApplication.translate("ui_constants", "關於")
    QCoreApplication.translate("ui_constants", "👻 作者資訊")
    QCoreApplication.translate("ui_constants", "逍遙 ( Xiao Yao )\n觀繁花而不與其爭艷\n處江湖而不染其煙塵")
    QCoreApplication.translate("ui_constants", "作者 Github 連結")
    QCoreApplication.translate("ui_constants", "📦 軟體資訊")
    QCoreApplication.translate("ui_constants", "版本: {version}\n一款用於編輯漫畫 ComicInfo 的編輯器")
    QCoreApplication.translate("ui_constants", "GitHub 專案連結")
    QCoreApplication.translate("ui_constants", "字體大小：")
    QCoreApplication.translate("ui_constants", "寫入模式：")
    QCoreApplication.translate("ui_constants", "原位置寫入")
    QCoreApplication.translate("ui_constants", "鋪平寫入")
    QCoreApplication.translate("ui_constants", "圖片附檔名：")
    QCoreApplication.translate("ui_constants", "允許檔案：")
    QCoreApplication.translate("ui_constants", "選擇漫畫資料夾")
    QCoreApplication.translate("ui_constants", "尚未選擇")
    QCoreApplication.translate("ui_constants", "手動")
    QCoreApplication.translate("ui_constants", "檔名")
    QCoreApplication.translate("ui_constants", "編號")
    QCoreApplication.translate("ui_constants", "排序依據：")
    QCoreApplication.translate("ui_constants", "已選中 {selected} / 共 {total} 本漫畫")
    QCoreApplication.translate("ui_constants", "選擇輸出資料夾")
    QCoreApplication.translate("ui_constants", "輸出副檔名：")
    QCoreApplication.translate("ui_constants", "開始處理")